# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7797a516-4a7a-4888-9a95-3079803d7bda";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A94C-AC77";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

    fileSystems."/tmp" = {
	  device = "tmpfs";
	  fsType = "tmpfs";
	  options = [ "defaults" "size=2G" "mode=1777" ];  # Removes noexec
	};

   fileSystems."/mnt/2TBHDD" = {
	device = "/dev/disk/by-uuid/144353bc-75d5-491a-b0b9-d21b170e1ddd";
	fsType = "ext4";
   };

   fileSystems."/mnt/1TBHDD" = {
	device = "/dev/disk/by-uuid/231d01d4-a7aa-4d2a-9cb3-658e47ccfbde";
	fsType = "ext4";
   }


  swapDevices =
    [ { device = "/dev/disk/by-uuid/2395c5c7-bfc3-40af-98f1-1daff7ea7e32"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
